// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function AbsentApplication(arg1:number):Promise<void>;

export function AbsentRegistration(arg1:number):Promise<void>;

export function Backup(arg1:string):Promise<void>;

export function ClearApplicationStatus(arg1:number):Promise<void>;

export function ClearRegistrationStatus(arg1:number):Promise<void>;

export function CloseRollCall(arg1:number):Promise<void>;

export function CreateRollCall(arg1:number):Promise<void>;

export function DeleteApprovedSelection():Promise<void>;

export function DeleteCall(arg1:number):Promise<void>;

export function DeleteInterestedSelection():Promise<void>;

export function DeleteRollCall(arg1:number):Promise<void>;

export function DeleteRollcall(arg1:number):Promise<void>;

export function Destroy():Promise<void>;

export function EmailPDF(arg1:number,arg2:string,arg3:string):Promise<void>;

export function EnrollApplication(arg1:number):Promise<void>;

export function EnrollRegistration(arg1:number):Promise<void>;

export function EnrollmentPDF(arg1:number,arg2:string,arg3:string):Promise<void>;

export function ExportCSV(arg1:string):Promise<void>;

export function FetchApplicationsByRollCall(arg1:number):Promise<Array<types.Registration>>;

export function FetchApprovedSelection():Promise<types.Selection>;

export function FetchInterestedSelection():Promise<types.Selection>;

export function FetchRegistration(arg1:number):Promise<types.RegistrationDetail>;

export function FetchRegistrations():Promise<Array<types.Registration>>;

export function FetchRegistrationsByCallID(arg1:number):Promise<Array<types.Registration>>;

export function FetchRegistrationsByCourseID(arg1:number):Promise<Array<types.Registration>>;

export function FetchRegistrationsBySelectionID(arg1:number):Promise<Array<types.Registration>>;

export function FetchRollCalls():Promise<Array<types.Call>>;

export function FetchSemesters():Promise<Array<types.Semester>>;

export function LoadApprovedSelection(arg1:number,arg2:string):Promise<void>;

export function LoadInterestedSelection(arg1:number,arg2:string):Promise<void>;

export function LoadWaitlistSelection(arg1:number,arg2:string):Promise<void>;

export function OpenCall(arg1:number):Promise<void>;

export function OpenFileDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function OpenRollCall(arg1:number):Promise<void>;

export function Restore(arg1:string):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function TeacherPDF(arg1:string,arg2:string):Promise<void>;

export function WebsitePDF(arg1:number,arg2:string,arg3:string):Promise<void>;
