// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AbsentApplication(arg1:number):Promise<main.Response>;

export function Backup():Promise<main.Response>;

export function ClearApplicationStatus(arg1:number):Promise<main.Response>;

export function CloseRollCall(arg1:number):Promise<main.Response>;

export function CreateRollCall():Promise<main.Response>;

export function DeleteApprovedSelection():Promise<main.Response>;

export function DeleteInterestedSelection():Promise<main.Response>;

export function DeleteRollcall(arg1:number):Promise<main.Response>;

export function Destroy():Promise<main.Response>;

export function EmailPDF(arg1:number,arg2:number):Promise<main.Response>;

export function EnrollApplication(arg1:number):Promise<main.Response>;

export function EnrollmentPDF(arg1:number,arg2:number):Promise<main.Response>;

export function ExportCSV():Promise<main.Response>;

export function FetchApplicationsByRollCall(arg1:number):Promise<main.Response>;

export function FetchApprovedSelection():Promise<main.Response>;

export function FetchInterestedSelection():Promise<main.Response>;

export function FetchPeriods():Promise<main.Response>;

export function FetchRollCalls():Promise<main.Response>;

export function LoadApprovedSelection():Promise<main.Response>;

export function LoadInterestedSelection():Promise<main.Response>;

export function OpenRollCall(arg1:number):Promise<main.Response>;

export function Restore():Promise<main.Response>;

export function TeacherPDF(arg1:number):Promise<main.Response>;

export function WebsitePDF(arg1:number,arg2:number):Promise<main.Response>;
