// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbsentApplication(arg1) {
  return window['go']['main']['App']['AbsentApplication'](arg1);
}

export function Backup() {
  return window['go']['main']['App']['Backup']();
}

export function ClearApplicationStatus(arg1) {
  return window['go']['main']['App']['ClearApplicationStatus'](arg1);
}

export function CloseRollCall(arg1) {
  return window['go']['main']['App']['CloseRollCall'](arg1);
}

export function CreateRollCall() {
  return window['go']['main']['App']['CreateRollCall']();
}

export function DeleteApprovedSelection() {
  return window['go']['main']['App']['DeleteApprovedSelection']();
}

export function DeleteInterestedSelection() {
  return window['go']['main']['App']['DeleteInterestedSelection']();
}

export function DeleteRollcall(arg1) {
  return window['go']['main']['App']['DeleteRollcall'](arg1);
}

export function Destroy() {
  return window['go']['main']['App']['Destroy']();
}

export function EmailPDF(arg1, arg2) {
  return window['go']['main']['App']['EmailPDF'](arg1, arg2);
}

export function EnrollApplication(arg1) {
  return window['go']['main']['App']['EnrollApplication'](arg1);
}

export function EnrollmentPDF(arg1, arg2) {
  return window['go']['main']['App']['EnrollmentPDF'](arg1, arg2);
}

export function ExportCSV() {
  return window['go']['main']['App']['ExportCSV']();
}

export function FetchApplicationsByRollCall(arg1) {
  return window['go']['main']['App']['FetchApplicationsByRollCall'](arg1);
}

export function FetchApprovedSelection() {
  return window['go']['main']['App']['FetchApprovedSelection']();
}

export function FetchInterestedSelection() {
  return window['go']['main']['App']['FetchInterestedSelection']();
}

export function FetchPeriods() {
  return window['go']['main']['App']['FetchPeriods']();
}

export function FetchRollCalls() {
  return window['go']['main']['App']['FetchRollCalls']();
}

export function LoadApprovedSelection() {
  return window['go']['main']['App']['LoadApprovedSelection']();
}

export function LoadInterestedSelection() {
  return window['go']['main']['App']['LoadInterestedSelection']();
}

export function OpenRollCall(arg1) {
  return window['go']['main']['App']['OpenRollCall'](arg1);
}

export function Restore() {
  return window['go']['main']['App']['Restore']();
}

export function TeacherPDF(arg1) {
  return window['go']['main']['App']['TeacherPDF'](arg1);
}

export function WebsitePDF(arg1, arg2) {
  return window['go']['main']['App']['WebsitePDF'](arg1, arg2);
}
